# This is the configuration for the revive linter used for linting the revive's codebase itself.
# See .github/workflows/lint.yaml.

ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

[rule.bare-return]
[rule.blank-imports]
[rule.comment-spacings]
[rule.constant-logical-expr]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.datarace]
[rule.deep-exit]
[rule.dot-imports]
[rule.empty-block]
[rule.empty-lines]
[rule.enforce-map-style]
    arguments = ["literal"]
[rule.enforce-slice-style]
    arguments = ["literal"]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.exported]
[rule.filename-format]
    # Override the default pattern to forbid .go files with uppercase letters and dashes.
    arguments=["^[_a-z][_a-z0-9]*\\.go$"]
[rule.identical-branches]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.line-length-limit]
    arguments = [200]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.redundant-build-tag]
[rule.superfluous-else]
[rule.time-date]
[rule.time-equal]
[rule.time-naming]
[rule.unexported-naming]
[rule.unexported-return]
[rule.unnecessary-format]
[rule.unnecessary-stmt]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.unused-receiver]
[rule.useless-break]
[rule.use-any]
[rule.use-fmt-print]
[rule.var-declaration]
[rule.var-naming]
