# This is the configuration for the revive linter used for linting the revive's codebase itself.
# See .github/workflows/lint.yaml.

ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

[rule.add-constant]
    disabled = true
[rule.argument-limit]
[rule.atomic]
[rule.banned-characters]
[rule.bare-return]
[rule.blank-imports]
[rule.bool-literal-in-expr]
[rule.call-to-gc]
[rule.comment-spacings]
[rule.comments-density]
[rule.confusing-naming]
    disabled = true
[rule.confusing-results]
[rule.constant-logical-expr]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.cyclomatic]
    disabled = true
[rule.datarace]
[rule.deep-exit]
[rule.defer]
[rule.dot-imports]
[rule.duplicated-imports]
[rule.early-return]
[rule.empty-block]
[rule.empty-lines]
[rule.enforce-map-style]
    arguments = ["literal"]
[rule.enforce-repeated-arg-type-style]
[rule.enforce-slice-style]
    arguments = ["literal"]
[rule.enforce-switch-style]
    arguments = ["allow-no-default"]
[rule.epoch-naming]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.exported]
[rule.file-header]
    disabled = true
[rule.file-length-limit]
    disabled = true
[rule.filename-format]
    # Override the default pattern to forbid .go files with uppercase letters and dashes.
    arguments=["^[_a-z][_a-z0-9]*\\.go$"]
[rule.flag-parameter]
    disabled = true
[rule.forbidden-call-in-wg-go]
[rule.function-length]
    disabled = true
[rule.function-result-limit]
[rule.get-return]
[rule.identical-branches]
[rule.identical-ifelseif-branches]
[rule.identical-ifelseif-conditions]
[rule.identical-switch-branches]
[rule.identical-switch-conditions]
[rule.if-return]
[rule.import-alias-naming]
[rule.import-shadowing]
[rule.imports-blocklist]
    arguments = ["sort"]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.inefficient-map-lookup]
[rule.line-length-limit]
    arguments = [200]
[rule.max-control-nesting]
[rule.max-public-structs]
    arguments = [10]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.nested-structs]
[rule.optimize-operands-order]
[rule.package-comments]
[rule.package-directory-mismatch]
[rule.range]
[rule.range-val-address]
[rule.range-val-in-closure]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.redundant-build-tag]
[rule.redundant-import-alias]
[rule.redundant-test-main-exit]
[rule.string-format]
[rule.string-of-int]
[rule.struct-tag]
    arguments = ["json,inline"]
[rule.superfluous-else]
[rule.time-date]
[rule.time-equal]
[rule.time-naming]
[rule.unchecked-type-assertion]
    disabled = true
[rule.unconditional-recursion]
[rule.unexported-naming]
[rule.unexported-return]
[rule.unhandled-error]
    disabled = true
[rule.unnecessary-format]
[rule.unnecessary-if]
[rule.unnecessary-stmt]
[rule.unreachable-code]
[rule.unsecure-url-scheme]
[rule.unused-parameter]
[rule.unused-receiver]
[rule.use-any]
[rule.use-errors-new]
[rule.use-fmt-print]
[rule.use-slices-sort]
[rule.use-waitgroup-go]
[rule.useless-break]
[rule.useless-fallthrough]
[rule.var-declaration]
[rule.var-naming]
[rule.waitgroup-by-value]
